DROP DATABASE IF EXISTS templator;

CREATE DATABASE IF NOT EXISTS templator;

USE templator;

CREATE TABLE IF NOT EXISTS users(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(50) NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	password VARCHAR(100) NOT NULL,
	image VARCHAR(500),
	mimetype VARCHAR(10),
	admin ENUM('y', 'n') NOT NULL DEFAULT 'n',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS subcategories(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	categoryid INT NOT NULL,
	title VARCHAR(50) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (categoryid)  REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS templates(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ownerid INT NOT NULL,
	subcategoryid INT NOT NULL,
	title VARCHAR(50) NOT NULL,
	description VARCHAR(500),
	version VARCHAR(30) NOT NULL,
	filepath VARCHAR(500),
	sourcetemplateid INT DEFAULT NULL,
	visibility ENUM('public', 'private') NOT NULL DEFAULT 'public',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (ownerid) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (subcategoryid) REFERENCES subcategories (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (sourcetemplateid) REFERENCES templates (id) ON DELETE SET NULL ON UPDATE CASCADE,
	INDEX (title)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tasks(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	taskid INT NOT NULL,
	title VARCHAR(50) NOT NULL,
	note VARCHAR(500),
	duration VARCHAR(30) NOT NULL,
	summarytaskid INT,
	templateid INT NOT NULL,
	predecessorids VARCHAR(100),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (templateid) REFERENCES templates (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
